## Background

Almost one-tenth of the [EU Multiannual Financial Framework](https://op.europa.eu/en/publication-detail/-/publication/d2cf202e-f36a-45b2-84e7-1ac6ad996e90) (MFF) is dedicated to research and innovation. This part of the budget, also known as the Framework Programme (FP) for research and innovation, aims a strengthening the European Research Area.  The Programmes are implemented by the Directorate-General for Research and Innovation and by a few Executive Agencies. FP7 stands for the 7th Framework Programme and corresponds to the MFF 2007-2013.  FP8, known as Horizon 2020 (H2020), refers to the 8th Framework Programme and corresponds to the MFF 2014-2020. The current FP, FP9, is known as Horizon Europe (HE) and corresponds to the MFF 2021-2027. 

Switzerland has been fully associated to the Framework Programmes since 2004 (for an overview, see [Swiss Participation in European Research Framework Programmes](https://www.sbfi.admin.ch/sbfi/en/home/research-and-innovation/international-cooperation-r-and-i/eu-framework-programmes-for-research/f-f-swiss-participation.html)). However, following the adoption of the "mass immigration" initiative of the 9th of February 2014, Switzerland was excluded at the start of H2020, in 2014. During 2015 and 2016 it became partially associated and regained full association in 2017 upon revision of its immigration law ([link](https://www.swissinfo.ch/eng/new-immigration-law-clears-final-hurdle/42769316)).
