---
title: "Extract, Load, and Transform"
author: "João Martins"
editor_options: 
  chunk_output_type: console
---

```{r boilerplate}
library(tidyverse)
library(janitor)
library(lubridate)
library(here)
library(glue)
library(readxl)
library(vroom)
library(yaml)
library(countrycode)
source(here("R", "utils.R"))
```


```{r extract-download-cordis-data, eval=FALSE}
"https://cordis.europa.eu/data/cordis-fp7projects-csv.zip" %>%
  download.file(here("data-raw", "cordis-fp7projects-csv.zip"))
unzip(
  here("data-raw", "cordis-fp7projects-csv.zip"),
  exdir = here("data-raw", "fp7")
)

"https://cordis.europa.eu/data/cordis-h2020projects-csv.zip" %>%
  download.file(here("data-raw", "cordis-h2020projects-csv.zip"))
unzip(
  here("data-raw", "cordis-h2020projects-csv.zip"),
  exdir = here("data-raw", "h2020")
)
```

> Qlik Sense dashboard data need to be downloaded by hand.  They contain useul attributes which are missing in the CORDIS records.

```{r load-dashboard-projects}
fp7_dashboard <- here("data-raw", "fp7-projects.xlsx") %>%
  read_excel() %>%
  clean_names() %>%
  select(
    project_id = project_nbr,
    thematic_priority = thematic_priority_descr,
    topic_code,
    topic_description,
    participations
  )

h2020_dashboard <- here("data-raw", "h2020-projects.xlsx") %>%
  read_excel() %>%
  clean_names() %>%
  select(
    project_id = project_nbr,
    thematic_priority = thema,
    topic_code,
    topic_description,
    participations = h2020_participations
  )

projects_dashboard <-
  fp7_dashboard %>%
  bind_rows(h2020_dashboard)

projects_cordis <-
  read_csv2(here("data-raw", "fp7", "csv", "project.csv")) %>%
  bind_rows(read_csv2(here("data-raw", "h2020", "csv", "project.csv"))) %>%
  clean_names() %>%
  select(
    project_id = id,
    rcn,
    proj_acronym = acronym,
    start_date,
    end_date,
    legal_basis,
    framework_programme,
    funding_scheme
  )

projects <- projects_cordis %>%
  left_join(projects_dashboard, by = "project_id")

rm(fp7_dashboard, h2020_dashboard, projects_dashboard, projects_cordis)
```

```{r, load-dashboard-organizations}
organizations_cordis <-
  read_csv2(here("data-raw", "fp7", "csv", "organization.csv")) %>%
  bind_rows(read_csv2(here(
    "data-raw", "h2020", "csv", "organization.csv"
  ))) %>%
  clean_names() %>%
  select(
    project_id,
    project_acronym,
    pic = organisation_id,
    legal_name = name,
    legal_short_name = short_name,
    legal_entity_type = activity_type,
    country_code = country,
    legal_url = organization_url,
    partner_role = role,
    ec_contribution,
    net_ec_contribution
  ) %>%
  mutate(net_ec_contribution = if_else(
    !is.na(net_ec_contribution),
    net_ec_contribution,
    ec_contribution
  ))

h2020_dashboard <- here("data-raw", "horizon2020.xlsx") %>%
  read_excel() %>%
  clean_names() %>%
  select(
    project_id = project_nbr,
    pic = general_pic,
    partner_role,
    pillar_abbr,
    pillar_descr,
    thematic_priority_abbr,
    signature_date,
    call_deadline_date,
    eu_contribution
  ) %>%
  mutate(partner_role = str_to_lower(partner_role))

organizations <- organizations_cordis %>%
  left_join(h2020_dashboard,
    by = c("project_id", "pic", "partner_role")
  )

rm(organizations_cordis, h2020_dashboard)
```


```{r transform}
df_raw <- organizations %>%
  left_join(projects, by = "project_id")

df_raw <- df_raw %>%
  mutate(
    # rename role
    partner_role = str_to_title(partner_role),
    pillar = str_extract(pillar_abbr, "\\d"),
    pillar = if_else(pillar_abbr == "EU.0.", "Cross-theme", pillar),
    pillar = if_else(pillar_abbr == "Euratom", pillar_abbr, pillar),
    legal_entity_type = str_sub(legal_entity_type, 1, 3),
    # import EU contribution
    eu_contribution = str_replace(eu_contribution, fixed("-"), "0"),
    eu_contribution = as.numeric(eu_contribution),
    # import country code
    country_code = str_sub(country_code, 1, 2),
    country = countrycode(country_code, "eurostat", "country.name.en"),
    # import dates
    signature_date = as.Date(signature_date, format = "%d/%m/%Y"),
    call_deadline_date = as.Date(call_deadline_date, format = "%d/%m/%Y"),
    signature_year = str_sub(signature_date, 1, 4),
    call_year = str_sub(call_deadline_date, 1, 4),
    start_year = str_sub(start_date, 1, 4),
    signature_year = int(signature_year),
    call_year = int(call_year),
    start_year = int(start_year)) %>%
  filter(!is.na(start_date))
```

```{r write}
df_schema <- df_raw %>%
  map_chr(class)

df_years <-
  df_raw %>%
  distinct(start_year) %>%
  pull() %>%
  sort()

df_raw <- df_raw %>%
  arrange(start_year) %>%
  group_by(start_year) %>%
  group_split() %>%
  setNames(df_years)

write_yaml(df_schema, here("data", "schema-cordis-plus.yml"))
file_names <- here("data", glue("cordis-plus-{df_years}.csv"))
walk2(df_raw, file_names, vroom_write, delim = ",")

```

