## Outlook

Horizon Europe's budget shows that the EU is divesting from Excellent Science, in not only relative, but also absolute terms, if one takes inflation rates into account.  Furthermore, both Switzerland and the United Kingdom have been top participants in Excellent Science in the previous Programmes, therefore important contributors to the competitiveness of European research.  Compared to FP7 and H2020, Horizon Europe risks being a step back for global competitiveness of European research if these two countries cannot participate as associated countries. For Switzerland, the exclusion from Horizon Europe results in either unfavorable conditions of participation for Swiss participants (eg. no right to coordinate projects), or exclusion from funding instruments.  This is the case for most of the Excellent Science pillar, which has also been the most important pillar for Switzerland in the previous Programmes.

Excluding Switzerland from Horizon Europe is ending a win-win agreement research collaboration between the EU and Switzerland and a setback to the initial goal of strengthening of the European Research Area. Stick to science.