---
title: "Reproducibility analylsis of SERI figures"
author: "João Martins"
output: 
  html_document: 
    theme: cerulean
    code_folding: hide
    toc: true
    toc_float: true
    self_contained: false
editor_options: 
  chunk_output_type: console
---

```{r boilerplate, message=FALSE, warning=FALSE}
# source code: https://github.com/zambujo/swissparticipation
library(tidyverse)
library(vroom)
library(janitor)
library(lubridate)
library(here)
library(yaml)
library(glue)
library(scales)
library(ggsci)
library(ggrepel)
library(ggtext)
library(reactable)
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
source(here("R", "utils.R"))
```

> Pease find related statistics on the SERI's page: [Facts and Figures on the Swiss Participation in the EU-Framework Programmes for Research and Innovation](https://www.sbfi.admin.ch/sbfi/en/home/research-and-innovation/international-cooperation-r-and-i/eu-framework-programmes-for-research/f-f-swiss-participation.html).


```{r read-dashboard-data}
df_schema <- here("data", "schema-cordis-plus.yml") %>%
  read_yaml() %>%
  as.list()

df_raw <-
  list.files(here("data"), pattern = "cordis-plus-", full.names = TRUE) %>%
  vroom(delim = ",", col_types = df_schema)
  # map_df(read_csv2, col_types = df_schema)

df_raw <-
  df_raw %>%
  mutate(
    pillar = fct_inseq(pillar),
    pillar = fct_rev(pillar),
    pillar = fct_relevel(pillar, "Cross-theme", after = 0),
    pillar = fct_recode(
      pillar, I = "1", II = "2", III = "3", IV = "4", V = "5"),
    org_type = fct_collapse(
      legal_entity_type,
      `Research & Education` = c("HES", "REC"),
      `Others (Excl. R&Ed)` = c("PRC", "PUB", "OTH")))

df <- df_raw %>%
  filter(framework_programme == "H2020") %>%
  filter(legal_name != "EUROPEAN ORGANIZATION FOR NUCLEAR RESEARCH")
```
