---
title: "FP7 & H2020 Figures"
output: 
  html_document:
    self_contained: no
---

```{r boilerplate, include=FALSE}
# source code: https://github.com/zambujo/swissparticipation
library(tidyverse)
library(vroom)
library(janitor)
library(lubridate)
library(here)
library(yaml)
library(glue)
library(scales)
library(ggsci)
library(ggrepel)
library(ggtext)
library(kableExtra)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = FALSE)
source(here("R", "utils.R"))
```


```{r read-dashboard-data}
df_schema <- here("data", "schema-cordis-plus.yml") %>%
  read_yaml() %>%
  as.list()

df_raw <-
  list.files(here("data"), pattern = "cordis-plus-", full.names = TRUE) %>%
  vroom(delim = ",", col_types = df_schema)
  # map_df(read_csv2, col_types = df_schema)

df_raw <-
  df_raw %>%
  mutate(
    pillar = fct_inseq(pillar),
    pillar = fct_rev(pillar),
    pillar = fct_relevel(pillar, "Cross-theme", after = 0),
    pillar = fct_recode(
      pillar, I = "1", II = "2", III = "3", IV = "4", V = "5"),
    org_type = fct_collapse(
      legal_entity_type,
      `Research & Education` = c("HES", "REC"),
      `Others (Excl. R&Ed)` = c("PRC", "PUB", "OTH")))

df <- df_raw %>%
    mutate(start_semester = floor_date(start_date, "6 months")) %>%
    # remove the CERN
    filter(legal_name != "EUROPEAN ORGANIZATION FOR NUCLEAR RESEARCH")
```

## An Overview of Swiss Participation  {.tabset .tabset-fade .tabset-pills}

```{r plot-styling}
bar_plt <- function(plt) {
  plt +
  geom_col() +
  theme_minimal() +
  theme(
    plot.title.position = "plot",
    text = element_text(
      size = 15,
      family = "Gill Sans",
      color = "gray15"
    )
  )
}

get_particip <- function(x, in_programme = "") {
  if (in_programme == "FP7") {
    x <- x %>%
      filter(framework_programme == "FP7")
  }
  if (in_programme == "H2020") {
    x <- x %>%
      filter(framework_programme == "H2020")
  }
  total <- x %>%
    count(year = start_year, name = "n_total")
  ch <- x %>%
    filter(country_code == "CH") %>%
    count(year = start_year, name = "n_ch")

  left_join(total, ch, by = "year") %>%
    mutate(share_particip = 100 * n_ch / n_total)
}

get_contrib <- function(x, in_programme = "") {
  if (in_programme == "FP7") {
    x <- x %>%
      filter(framework_programme == "FP7")
  }
  if (in_programme == "H2020") {
    x <- x %>%
      filter(framework_programme == "H2020")
  }
  to_all <- x %>%
    group_by(year = start_year) %>%
    summarise(contrib_all = sum(re_contribution, na.rm = TRUE))
  to_ch <- x %>%
    filter(country_code == "CH") %>%
    group_by(year = start_year) %>%
    summarise(contrib_ch = sum(re_contribution, na.rm = TRUE))

  left_join(to_all, to_ch, by = "year") %>%
    mutate(share_contrib = 100 * contrib_ch / contrib_all)
}

get_coord <- function(x, in_programme = "") {
  if (in_programme == "FP7") {
    x <- x %>%
      filter(framework_programme == "FP7")
  }
  if (in_programme == "H2020") {
    x <- x %>%
      filter(framework_programme == "H2020")
  }
  
  all <- x %>%
    filter(partner_role == "Coordinator") %>%
    count(year = start_year, name = "coord_total")
  ch <- x %>%
    filter(country_code == "CH") %>%
    filter(partner_role == "Coordinator") %>%
    count(year = start_year, name = "coord_ch")

  left_join(all, ch, by = "year") %>%
    mutate(share_contrib = 100 * coord_ch / coord_total)
}
```

SERI figures show slightly higher shares of contributions to Swiss participants. They should, nevertheless, exclude the CERN, the UN, and UN-affiliated institutions.

### Share Swiss Participations

```{r swiss-participations}
df %>%
  get_particip() %>%
  ggplot(aes(x = year, y = share_particip)) %>%
  bar_plt() +
  labs(
    title = "Swiss Participation",
    subtitle = "By project starting year, FP7 and H2020",
    x = "Project Starting Year",
    y = "%"
  ) +
  annotate(
    "rect",
    xmin = 2006.5,
    xmax = 2014.5,
    ymin = -.1,
    ymax = 3.55,
    fill = "#21325E",
    alpha = .1
  ) +
  annotate(
    "rect",
    xmin = 2014.5,
    xmax = 2022.5,
    ymin = -.1,
    ymax = 3.55,
    fill = "#F1D00A",
    alpha = .1
  ) +
  annotate(
    "text",
    x = c(2010, 2019),
    y = c(3.65, 3.65),
    label = c("FP7", "H2020"),
    family = "Gill Sans"
  )
```

```{r swiss-participations-fp7, include=FALSE}
df %>%
  get_particip(in_programme = "FP7") %>%
  select(n_ch, n_total) %>%
  summarise_all(sum, na.rm = TRUE) %>%
  mutate(share = round(100 * n_ch / n_total, 1)) %>%
  kbl()
```

```{r swiss-participations-h2020, include=FALSE}
df %>%
  get_particip(in_programme = "H2020") %>%
  select(n_ch, n_total) %>%
  summarise_all(sum, na.rm = TRUE) %>%
  mutate(share = round(100 * n_ch / n_total, 1)) %>%
  kbl()
```

### Contribution to Swiss Participants

```{r swiss-countributions}
df %>%
  get_contrib() %>%
  ggplot(aes(x = year, y = share_contrib)) %>%
  bar_plt() +
  labs(
    title = "Contributions to Swiss Participants",
    subtitle = "By project starting year, FP7 and H2020",
    x = "Project Starting Year",
    y = "%"
  ) +
  annotate(
    "rect",
    xmin = 2006.5,
    xmax = 2014.5,
    ymin = -.1,
    ymax = 5.75,
    fill = "#21325E",
    alpha = .1
  ) +
  annotate(
    "rect",
    xmin = 2014.5,
    xmax = 2022.5,
    ymin = -.1,
    ymax = 5.75,
    fill = "#F1D00A",
    alpha = .1
  ) +
  annotate(
    "text",
    x = c(2010, 2019),
    y = c(6, 6),
    label = c("FP7", "H2020"),
    family = "Gill Sans"
  )
```

```{r contributions-ch-fp7, include=FALSE}
df %>%
  get_contrib(in_programme = "FP7") %>%
  select(contrib_ch, contrib_all) %>%
  summarise_all(sum, na.rm = TRUE) %>%
  mutate(share = round(100 * contrib_ch / contrib_all, 1)) %>%
  kbl()
```

```{r contributions-ch-h2020, include=FALSE}
df %>%
  get_contrib(in_programme = "H2020") %>%
  select(contrib_ch, contrib_all) %>%
  summarise_all(sum, na.rm = TRUE) %>%
  mutate(share = round(100 * contrib_ch / contrib_all, 1)) %>%
  kbl()
```

### Swiss Coordinations

```{r coordinations-overviews}
df %>%
  get_coord() %>%
  ggplot(aes(x = year, y = share_contrib)) %>%
  bar_plt() +
  labs(
    title = "Swiss Coordinations",
    subtitle = "By project starting year, FP7 and H2020",
    x = "Project Starting Year",
    y = "%"
  ) +
  annotate(
    "rect",
    xmin = 2006.5,
    xmax = 2014.5,
    ymin = -.1,
    ymax = 5.6,
    fill = "#21325E",
    alpha = .1
  ) +
  annotate(
    "rect",
    xmin = 2014.5,
    xmax = 2022.5,
    ymin = -.1,
    ymax = 5.6,
    fill = "#F1D00A",
    alpha = .1
  ) +
  annotate(
    "text",
    x = c(2010, 2019),
    y = c(5.8, 5.8),
    label = c("FP7", "H2020"),
    family = "Gill Sans"
  )
```

```{r coordinations-ch-fp7, include=FALSE}
df %>%
  get_coord(in_programme = "FP7") %>%
  select(coord_ch, coord_total) %>%
  summarise_all(sum, na.rm = TRUE) %>%
  mutate(share = round(100 * coord_ch / coord_total, 1)) %>%
  kbl()
```

```{r coordinations-ch-h2020, include=FALSE}
df %>%
  get_coord(in_programme = "H2020") %>%
  select(coord_ch, coord_total) %>%
  summarise_all(sum, na.rm = TRUE) %>%
  mutate(share = round(100 * coord_ch / coord_total, 1)) %>%
  kbl()
```

